In [1]:
from pathlib import Path

dossier = Path("data")

fichiers_csv = list(dossier.glob("*.csv"))

print("Nombre de fichiers CSV :", len(fichiers_csv))

for fichier in fichiers_csv:
    print(fichier.name)

Nombre de fichiers CSV : 0

In [2]:
from pathlib import Path

dossier = Path("data")

fichiers_csv = list(dossier.glob("*.csv"))

print("Nombre de fichiers CSV :", len(fichiers_csv))

for fichier in fichiers_csv:
    print(fichier.name)

Nombre de fichiers CSV : 0

In [3]:
from pathlib import Path

print(Path.cwd())
print(list(Path.cwd().iterdir()))

c:\Users\chris\OneDrive\Bureau\Administratif\Chris\Bootcamp data analyst\Fil rouge\projet coupe du monde\data
[WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/01.exploration.ipynb'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1930.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1934.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1938.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1950.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1954.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1958.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1962.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1966.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1970.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1974.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1978.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1982.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1986.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1990.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1994.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 1998.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2002.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2006.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2010.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2014.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2018.csv'), WindowsPath('c:/Users/chris/OneDrive/Bureau/Administratif/Chris/Bootcamp data analyst/Fil rouge/projet coupe du monde/data/FIFA - 2022.csv')]

In [4]:
from pathlib import Path

fichiers_csv = list(Path(".").glob("*.csv"))

print("Nombre de fichiers CSV :", len(fichiers_csv))

for fichier in fichiers_csv:
    print(fichier.name)

Nombre de fichiers CSV : 22
FIFA - 1930.csv
FIFA - 1934.csv
FIFA - 1938.csv
FIFA - 1950.csv
FIFA - 1954.csv
FIFA - 1958.csv
FIFA - 1962.csv
FIFA - 1966.csv
FIFA - 1970.csv
FIFA - 1974.csv
FIFA - 1978.csv
FIFA - 1982.csv
FIFA - 1986.csv
FIFA - 1990.csv
FIFA - 1994.csv
FIFA - 1998.csv
FIFA - 2002.csv
FIFA - 2006.csv
FIFA - 2010.csv
FIFA - 2014.csv
FIFA - 2018.csv
FIFA - 2022.csv

In [5]:
import pandas as pd

df = pd.read_csv(fichiers_csv[0])

df.head()

,Position,Team,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points
0,1,Uruguay,4,4,0,0,15,3,12,8
1,2,Argentina,5,4,0,1,18,9,9,8
2,3,United States,3,2,0,1,7,6,1,4
3,4,Yugoslavia,3,2,0,1,7,7,0,4
4,5,Chile,3,2,0,1,5,3,2,4

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Position         13 non-null     int64
 1   Team             13 non-null     object
 2   Games Played     13 non-null     int64
 3   Win              13 non-null     int64
 4   Draw             13 non-null     int64
 5   Loss             13 non-null     int64
 6   Goals For        13 non-null     int64
 7   Goals Against    13 non-null     int64
 8   Goal Difference  13 non-null     object
 9   Points           13 non-null     int64
dtypes: int64(8), object(2)
memory usage: 1.1+ KB

In [7]:
df["Goal Difference"].unique()

array(['12', '9', '1', '0', '2', '3', '−2', '−3', '−4', '−8', '−9'],
      dtype=object)

In [8]:
print(repr(df["Goal Difference"].iloc[6]))

'1'

In [9]:
print(df["Goal Difference"].head(10).tolist())

['12', '9', '1', '0', '2', '3', '1', '−2', '−2', '−3']

In [10]:
print(repr(df["Goal Difference"].iloc[7]))

'−2'

In [11]:
print("Moins typographique :", "−" in df["Goal Difference"].iloc[7])
print("Moins classique :", "-" in df["Goal Difference"].iloc[7])

Moins typographique : True
Moins classique : False

In [12]:
df["Goal Difference"] = (
    df["Goal Difference"]
    .str.replace("−", "-", regex=False)
    .astype(int)
)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Position         13 non-null     int64
 1   Team             13 non-null     object
 2   Games Played     13 non-null     int64
 3   Win              13 non-null     int64
 4   Draw             13 non-null     int64
 5   Loss             13 non-null     int64
 6   Goals For        13 non-null     int64
 7   Goals Against    13 non-null     int64
 8   Goal Difference  13 non-null     int64
 9   Points           13 non-null     int64
dtypes: int64(9), object(1)
memory usage: 1.1+ KB

In [14]:
df.describe()

,Position,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points
count,13.00000,13.000000,13.000000,13.0,13.000000,13.000000,13.000000,13.000000,13.000000
mean,7.00000,2.769231,1.384615,0.0,1.384615,5.384615,5.384615,0.000000,2.769231
std,3.89444,0.926809,1.386750,0.0,0.767948,5.500583,3.150092,5.901977,2.773501
min,1.00000,2.000000,0.000000,0.0,0.000000,0.000000,2.000000,-9.000000,0.000000
25%,4.00000,2.000000,0.000000,0.0,1.000000,1.000000,3.000000,-3.000000,0.000000
50%,7.00000,3.000000,1.000000,0.0,1.000000,4.000000,4.000000,0.000000,2.000000
75%,10.00000,3.000000,2.000000,0.0,2.000000,7.000000,7.000000,2.000000,4.000000
max,13.00000,5.000000,4.000000,0.0,3.000000,18.000000,13.000000,12.000000,8.000000

In [15]:
df.describe().T

                 count      mean       std  min  25%  50%   75%   max
Position          13.0  7.000000  3.894440  1.0  4.0  7.0  10.0  13.0
Games Played      13.0  2.769231  0.926809  2.0  2.0  3.0   3.0   5.0
Win               13.0  1.384615  1.386750  0.0  0.0  1.0   2.0   4.0
Draw              13.0  0.000000  0.000000  0.0  0.0  0.0   0.0   0.0
Loss              13.0  1.384615  0.767948  0.0  1.0  1.0   2.0   3.0
Goals For         13.0  5.384615  5.500583  0.0  1.0  4.0   7.0  18.0
Goals Against     13.0  5.384615  3.150092  2.0  3.0  4.0   7.0  13.0
Goal Difference   13.0  0.000000  5.901977 -9.0 -3.0  0.0   2.0  12.0
Points            13.0  2.769231  2.773501  0.0  0.0  2.0   4.0   8.0

In [16]:
df.shape

(13, 10)

In [17]:
df.columns

Index(['Position', 'Team', 'Games Played', 'Win', 'Draw', 'Loss', 'Goals For',
       'Goals Against', 'Goal Difference', 'Points'],
      dtype='object')

In [18]:
df["Team"]

0           Uruguay
1         Argentina
2     United States
3        Yugoslavia
4             Chile
5            Brazil
6            France
7           Romania
8          Paraguay
9              Peru
10          Belgium
11          Bolivia
12           Mexico
Name: Team, dtype: object

In [19]:
df["Goals For"]

0     15
1     18
2      7
3      7
4      5
5      5
6      4
7      3
8      1
9      1
10     0
11     0
12     4
Name: Goals For, dtype: int64