Analyse des données des Coupes du monde :

Objectif

Analyser les performances des équipes lors des Coupes du monde de football de 1930 à 2022, puis étudier les résultats des pays organisateurs.

In [1]:
import pandas as pd

df_fifa = pd.read_csv("../outputs/fifa_prepared.csv")

In [2]:
df_fifa.shape

(489, 13)

Nous commençons par une première analyse descriptive, pour comprendre les données avant de poser des questions plus précises.

In [3]:
df_fifa.describe()

,Position,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points,Year
count,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000
mean,12.838446,3.938650,1.541922,0.854806,1.541922,5.560327,5.560327,0.000000,4.730061,1987.186094
std,8.306900,1.469749,1.550641,0.864476,0.778016,4.527346,2.748498,4.733037,4.151429,26.098178
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-16.000000,0.000000,1930.000000
25%,6.000000,3.000000,0.000000,0.000000,1.000000,2.000000,4.000000,-3.000000,2.000000,1970.000000
50%,12.000000,3.000000,1.000000,1.000000,2.000000,4.000000,5.000000,-1.000000,4.000000,1994.000000
75%,18.000000,5.000000,2.000000,1.000000,2.000000,8.000000,7.000000,2.000000,7.000000,2010.000000
max,32.000000,7.000000,7.000000,4.000000,3.000000,27.000000,16.000000,17.000000,21.000000,2022.000000

Description des statistiques descriptives :

Le jeu de données comprend 489 observations pour chacune des colonnes numériques.

Le nombre de matchs joués (Games Played) varie de 1 à 32, avec une moyenne de 12,84 et une médiane de 12.

Le nombre de victoires (Win) varie de 0 à 7, avec une moyenne de 3,94. Le nombre de matchs nuls (Draw) varie de 0 à 7, et celui des défaites (Loss) de 0 à 4.

Le nombre de buts marqués (Goals For) varie de 0 à 27, avec une moyenne de 5,56. Le nombre de buts encaissés (Goals Against) varie également de 0 à 27, avec une moyenne de 5,56.

La différence de buts (Goal Difference) varie de -16 à 16. Les points (Points) varient de -16 à 17.

Enfin, les années représentées dans le jeu de données vont de 1930 à 2022.

Question : quelles équipes ont participé le plus souvent aux Coupes du monde ?

In [4]:
df_fifa["Team_Harmonized"].value_counts()

Team_Harmonized
Brazil                    22
Germany                   20
Italy                     18
Argentina                 18
Mexico                    17
                          ..
Slovakia                   1
Bosnia and Herzegovina     1
Iceland                    1
Panama                     1
Qatar                      1
Name: count, Length: 80, dtype: int64

Le jeu de données compte 80 valeurs distinctes dans Team_Harmonized.

Le Brésil apparaît le plus souvent, avec 22 participations.

L'Allemagne apparaît 20 fois, puis l'Italie et l'Argentine 18 fois chacune.

À l'inverse, plusieurs équipes n'apparaissent qu'une seule fois, comme la Slovaquie, l'Islande, le Panama et le Qatar.

En rappelant que le comptage dépend de notre harmonisation des noms historiques.

In [5]:
df_fifa["Team_Harmonized"].value_counts().head(10)

Team_Harmonized
Brazil       22
Germany      20
Italy        18
Argentina    18
Mexico       17
France       16
England      16
Spain        16
Belgium      14
Uruguay      14
Name: count, dtype: int64

Question : quelles équipes ont marqué le plus de buts au total sur toutes les éditions ?

In [6]:
df_fifa.groupby("Team_Harmonized")["Goals For"].sum().sort_values(ascending=False).head(10)

Team_Harmonized
Brazil         237
Germany        232
Argentina      152
France         136
Italy          127
Spain          108
England        104
Netherlands     96
Uruguay         89
Hungary         87
Name: Goals For, dtype: int64

Le Brésil arrive en tête avec 237 buts, suivi de l'Allemagne avec 232. L'Argentine occupe la troisième place avec 152 buts. Ce classement ne tient en revanche pas compte du nombre de matchs joués.

Calculer les buts marqués par match

In [9]:
stats_equipes = df_fifa.groupby("Team_Harmonized")[["Goals For", "Games Played"]].sum()

stats_equipes

                      Goals For  Games Played
Team_Harmonized
Algeria                      13            13
Angola                        1             3
Argentina                   152            88
Australia                    17            20
Austria                      43            29
...                         ...           ...
Ukraine                       5             5
United Arab Emirates          2             3
United States                40            37
Uruguay                      89            59
Wales                         5             8

[80 rows x 2 columns]

In [10]:
stats_equipes["Goals For"] / stats_equipes["Games Played"]

Team_Harmonized
Algeria                 1.000000
Angola                  0.333333
Argentina               1.727273
Australia               0.850000
Austria                 1.482759
                          ...
Ukraine                 1.000000
United Arab Emirates    0.666667
United States           1.081081
Uruguay                 1.508475
Wales                   0.625000
Length: 80, dtype: float64

In [11]:
stats_equipes["Goals Per Match"] = (
    stats_equipes["Goals For"] / stats_equipes["Games Played"]
)

stats_equipes

                      Goals For  Games Played  Goals Per Match
Team_Harmonized
Algeria                      13            13         1.000000
Angola                        1             3         0.333333
Argentina                   152            88         1.727273
Australia                    17            20         0.850000
Austria                      43            29         1.482759
...                         ...           ...              ...
Ukraine                       5             5         1.000000
United Arab Emirates          2             3         0.666667
United States                40            37         1.081081
Uruguay                      89            59         1.508475
Wales                         5             8         0.625000

[80 rows x 3 columns]

In [12]:
stats_equipes.sort_values(
    by="Goals Per Match",
    ascending=False
).head(10)

                 Goals For  Games Played  Goals Per Match
Team_Harmonized
Hungary                 87            32         2.718750
Brazil                 237           114         2.078947
Germany                232           112         2.071429
Turkey                  20            10         2.000000
France                 136            73         1.863014
Netherlands             96            55         1.745455
Portugal                61            35         1.742857
Argentina              152            88         1.727273
Russia                  77            45         1.711111
Cuba                     5             3         1.666667

In [13]:
stats_equipes["Goals Per Match"] = stats_equipes["Goals Per Match"].round(2)

stats_equipes.sort_values(
    by="Goals Per Match",
    ascending=False
).head(10)

                 Goals For  Games Played  Goals Per Match
Team_Harmonized
Hungary                 87            32             2.72
Brazil                 237           114             2.08
Germany                232           112             2.07
Turkey                  20            10             2.00
France                 136            73             1.86
Netherlands             96            55             1.75
Portugal                61            35             1.74
Argentina              152            88             1.73
Russia                  77            45             1.71
Cuba                     5             3             1.67

Comparer les pays hôtes aux autres équipes

Combien de victoires les équipes hôtes et les équipes non hôtes ont-elles cumulées ?

In [14]:
df_fifa.groupby("Host")["Win"].sum()

Host
False    681
True      73
Name: Win, dtype: int64

681 victoires pour les équipes non organisatrices.
73 victoires pour les équipes organisatrices.

On ne peut toutefois pas conclure que les pays organisateurs gagnent moins souvent à partir de ces seuls totaux. Il y a beaucoup plus de lignes pour les équipes non organisatrices (466 contre 23).

Comparaison des victoires au nombre de matchs joués
On va obtenir, pour chaque groupe, le nombre total de victoires et le nombre total de matchs joués. Cela nous permettra de calculer une proportion de victoires par match joué, plus pertinente que de comparer les totaux seuls.

In [15]:
df_fifa.groupby("Host")[["Win", "Games Played"]].sum()

       Win  Games Played
Host
False  681          1806
True    73           120

Cependant à présent nous allons nous intéresser à qui sont les pays hôtes et si le fait d'avoir accueilli une coupe du monde leur permet d'avoir un résultat différent que lorsqu'ils n'organisent pas.

In [16]:
df_fifa[["Year", "Team", "Team_Harmonized", "Position", "Host"]].head(10)

   Year           Team Team_Harmonized  Position   Host
0  1930        Uruguay         Uruguay         1   True
1  1930      Argentina       Argentina         2  False
2  1930  United States   United States         3  False
3  1930     Yugoslavia          Serbia         4  False
4  1930          Chile           Chile         5  False
5  1930         Brazil          Brazil         6  False
6  1930         France          France         7  False
7  1930        Romania         Romania         8  False
8  1930       Paraguay        Paraguay         9  False
9  1930           Peru            Peru        10  False

In [17]:
pays_hotes = df_fifa.loc[df_fifa["Host"], "Team_Harmonized"].unique()

pays_hotes

array(['Uruguay', 'Italy', 'France', 'Brazil', 'Switzerland', 'Sweden',
       'Chile', 'England', 'Mexico', 'Germany', 'Argentina', 'Spain',
       'United States', 'South Korea', 'Japan', 'South Africa', 'Russia',
       'Qatar'], dtype=object)

On veut maintenant conserver toutes les lignes correspondant aux 18 pays, y compris lorsqu'ils n'organisent pas la compétition.

In [18]:
df_pays_hotes = df_fifa[
    df_fifa["Team_Harmonized"].isin(pays_hotes)
]

df_pays_hotes.shape

(234, 13)

In [19]:
df_pays_hotes["Host"].value_counts()

Host
False    211
True      23
Name: count, dtype: int64

In [20]:
comparaison_host = df_pays_hotes.groupby("Host").agg(
    Victoires=("Win", "sum"),
    Matchs_joues=("Games Played", "sum"),
    Position_moyenne=("Position", "mean")
)

comparaison_host

       Victoires  Matchs_joues  Position_moyenne
Host
False        396           890         10.317536
True          73           120          6.391304

première observation, les pays hôtes ont une position finale moyenne meilleure que lorsqu'ils participent sans être hôtes, dans les données que nous avons sélectionnées.

In [21]:
comparaison_host["Victoires_par_match"] = (
    comparaison_host["Victoires"] / comparaison_host["Matchs_joues"]
)

comparaison_host

       Victoires  Matchs_joues  Position_moyenne  Victoires_par_match
Host
False        396           890         10.317536             0.444944
True          73           120          6.391304             0.608333

In [22]:
df_pays_hotes.groupby("Host")["Position"].count()

Host
False    211
True      23
Name: Position, dtype: int64

In [23]:
comparaison_host.round(2)

       Victoires  Matchs_joues  Position_moyenne  Victoires_par_match
Host
False        396           890             10.32                 0.44
True          73           120              6.39                 0.61

Analyse comparative des pays hôtes et non hôtes :

Objectif :

L'objectif est d'observer si les pays organisateurs obtiennent de meilleurs résultats lorsqu'ils accueillent la Coupe du monde que lorsqu'ils y participent sans être pays hôte.

L'analyse porte sur les 18 pays ayant accueilli au moins une édition, en comparant leurs participations à domicile et hors domicile.

Résultats :

Les résultats obtenus sont les suivants :

La proportion de victoires par match joué est plus élevée lorsque les pays organisent la compétition : 61 % contre 44 % lorsqu'ils ne sont pas hôtes.

La position finale moyenne est également meilleure lors des éditions organisées par ces pays. Elle est de 6,39 à domicile contre 10,32 hors domicile. Une position plus faible correspondant à un meilleur classement, cette observation va dans le sens de l'hypothèse d'un avantage du pays organisateur.

Limites de l'analyse :

Des effectifs différents : l'analyse repose sur 23 participations en tant que pays hôte contre 211 participations hors domicile. Le nombre de participations à domicile est donc relativement faible.

Des périodes historiques différentes : les données couvrent les éditions de 1930 à 2022. Le niveau des équipes, les formats de compétition et le nombre de matchs joués ont évolué au fil du temps.

Des performances variables selon les pays : les résultats dépendent notamment du niveau sportif de chaque équipe et de son évolution d'une édition à l'autre.

Une harmonisation des noms : certaines équipes historiques ont été regroupées sous un même nom de référence. Cette convention facilite les comparaisons, mais peut influencer les résultats.

Une relation qui ne démontre pas une causalité : les données montrent une différence de résultats entre les deux situations, mais ne permettent pas d'affirmer que l'organisation de la compétition est à elle seule responsable de cette différence.

Conclusion :

Dans les données étudiées, les pays hôtes présentent une proportion de victoires plus élevée et une meilleure position finale moyenne que lors de leurs participations hors domicile.

Ces observations sont compatibles avec l'hypothèse d'un avantage du pays organisateur. Elles doivent toutefois être interprétées avec prudence, compte tenu des différences d'effectifs, des évolutions historiques et des performances propres à chaque équipe.